"""initial production schema

Revision ID: cba2490cda76
Revises: 
Create Date: 2026-07-14 12:36:26.392749
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cba2490cda76'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_dataset_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('baseline_run_id', sa.String(length=36), nullable=True),
    sa.Column('gate_policy_json', sa.JSON(), nullable=False),
    sa.Column('cases_json', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'version', name='uq_evaluation_dataset_snapshot_version')
    )
    with op.batch_alter_table('evaluation_dataset_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_dataset_snapshots_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_dataset_snapshots_task_type'), ['task_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_dataset_snapshots_version'), ['version'], unique=False)

    op.create_table('evaluation_datasets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('baseline_run_id', sa.String(length=36), nullable=True),
    sa.Column('gate_policy_json', sa.JSON(), nullable=False),
    sa.Column('cases_json', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_datasets_baseline_run_id'), ['baseline_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_datasets_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_datasets_task_type'), ['task_type'], unique=False)

    op.create_table('evaluation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=True),
    sa.Column('dataset_version', sa.Integer(), nullable=True),
    sa.Column('dataset_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('case_count', sa.Integer(), nullable=False),
    sa.Column('passed_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('request_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_runs_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_runs_dataset_snapshot_id'), ['dataset_snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_runs_task_type'), ['task_type'], unique=False)

    op.create_table('mcp_server_health',
    sa.Column('server_name', sa.String(length=64), nullable=False),
    sa.Column('public_url', sa.String(length=2048), nullable=True),
    sa.Column('circuit_state', sa.String(length=16), nullable=False),
    sa.Column('manual_open', sa.Boolean(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('total_transport_successes', sa.Integer(), nullable=False),
    sa.Column('total_transport_failures', sa.Integer(), nullable=False),
    sa.Column('circuit_rejections', sa.Integer(), nullable=False),
    sa.Column('circuit_open_count', sa.Integer(), nullable=False),
    sa.Column('total_probes', sa.Integer(), nullable=False),
    sa.Column('failed_probes', sa.Integer(), nullable=False),
    sa.Column('last_probe_status', sa.String(length=16), nullable=False),
    sa.Column('last_probe_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(), nullable=True),
    sa.Column('last_latency_ms', sa.Float(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('protocol_version', sa.String(length=64), nullable=True),
    sa.Column('server_info_json', sa.JSON(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(), nullable=True),
    sa.Column('half_open_trial_id', sa.String(length=64), nullable=True),
    sa.Column('half_open_lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('server_name')
    )
    with op.batch_alter_table('mcp_server_health', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_server_health_circuit_state'), ['circuit_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_server_health_cooldown_until'), ['cooldown_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_server_health_last_probe_status'), ['last_probe_status'], unique=False)

    op.create_table('mcp_server_registrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('allowed_tools_json', sa.JSON(), nullable=False),
    sa.Column('tool_policies_json', sa.JSON(), nullable=False),
    sa.Column('agent_context_tools_json', sa.JSON(), nullable=False),
    sa.Column('idempotency_mode', sa.String(length=32), nullable=False),
    sa.Column('validation_status', sa.String(length=32), nullable=False),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('protocol_version', sa.String(length=64), nullable=True),
    sa.Column('server_info_json', sa.JSON(), nullable=True),
    sa.Column('capabilities_json', sa.JSON(), nullable=True),
    sa.Column('tools_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcp_server_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_server_registrations_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_server_registrations_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_mcp_server_registrations_validation_status'), ['validation_status'], unique=False)

    op.create_table('mcp_tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('client_token_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcp_tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_tenants_slug'), ['slug'], unique=True)

    op.create_table('mcp_credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('server_id', sa.String(length=36), nullable=False),
    sa.Column('auth_type', sa.String(length=32), nullable=False),
    sa.Column('encrypted_payload', sa.Text(), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_server_registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcp_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_credentials_server_id'), ['server_id'], unique=True)

    op.create_table('mcp_delegated_oauth_providers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('server_name', sa.String(length=64), nullable=False),
    sa.Column('authorization_url', sa.String(length=2048), nullable=False),
    sa.Column('token_url', sa.String(length=2048), nullable=False),
    sa.Column('client_id', sa.String(length=1024), nullable=False),
    sa.Column('encrypted_client_secret', sa.Text(), nullable=True),
    sa.Column('scopes_json', sa.JSON(), nullable=False),
    sa.Column('redirect_uri', sa.String(length=2048), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['mcp_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'server_name', name='uq_mcp_delegated_provider_server')
    )
    with op.batch_alter_table('mcp_delegated_oauth_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_delegated_oauth_providers_server_name'), ['server_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_delegated_oauth_providers_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('mcp_server_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('server_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_server_registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcp_server_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_server_revisions_server_id'), ['server_id'], unique=False)

    op.create_table('mcp_tenant_memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['mcp_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'provider', 'subject', name='uq_mcp_tenant_member')
    )
    with op.batch_alter_table('mcp_tenant_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_tenant_memberships_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('mcp_tenant_server_bindings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('server_name', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['mcp_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'server_name', name='uq_mcp_tenant_server')
    )
    with op.batch_alter_table('mcp_tenant_server_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_tenant_server_bindings_server_name'), ['server_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_tenant_server_bindings_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('repositories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('repo_url', sa.Text(), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('language_summary', sa.JSON(), nullable=False),
    sa.Column('last_commit_hash', sa.String(length=64), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('memory_summary', sa.Text(), nullable=True),
    sa.Column('memory_data', sa.JSON(), nullable=False),
    sa.Column('memory_updated_at', sa.DateTime(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['mcp_tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repositories_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_repositories_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('code_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repo_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('imports', sa.JSON(), nullable=False),
    sa.Column('exports', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'file_path', name='uq_code_files_repo_path')
    )
    with op.batch_alter_table('code_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_code_files_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_files_repo_id'), ['repo_id'], unique=False)

    op.create_table('evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evaluation_run_id', sa.String(length=36), nullable=True),
    sa.Column('case_id', sa.String(length=128), nullable=True),
    sa.Column('repo_id', sa.String(length=36), nullable=True),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('expected_file', sa.Text(), nullable=True),
    sa.Column('expected_lines', sa.JSON(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('failure_category', sa.String(length=128), nullable=True),
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluations_evaluation_run_id'), ['evaluation_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluations_repo_id'), ['repo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluations_task_type'), ['task_type'], unique=False)

    op.create_table('mcp_access_grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('repo_id', sa.String(length=36), nullable=True),
    sa.Column('principal_type', sa.String(length=32), nullable=False),
    sa.Column('principal_id', sa.String(length=255), nullable=False),
    sa.Column('server_name', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('permissions_json', sa.JSON(), nullable=False),
    sa.Column('effect', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['mcp_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcp_access_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_access_grants_principal_id'), ['principal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_access_grants_principal_type'), ['principal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_access_grants_repo_id'), ['repo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_access_grants_server_name'), ['server_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_access_grants_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_access_grants_tool_name'), ['tool_name'], unique=False)

    op.create_table('mcp_delegated_identities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('server_name', sa.String(length=64), nullable=False),
    sa.Column('subject_provider', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('encrypted_token_payload', sa.Text(), nullable=False),
    sa.Column('delegation_token_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes_json', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['mcp_delegated_oauth_providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['mcp_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcp_delegated_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_delegated_identities_revoked'), ['revoked'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_delegated_identities_server_name'), ['server_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_delegated_identities_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_delegated_identities_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('mcp_delegated_oauth_states',
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('subject_provider', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('encrypted_verifier', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['mcp_delegated_oauth_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('state_hash')
    )
    with op.batch_alter_table('mcp_delegated_oauth_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_delegated_oauth_states_expires_at'), ['expires_at'], unique=False)

    op.create_table('mcp_quota_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope_key', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('repo_id', sa.String(length=36), nullable=True),
    sa.Column('principal_type', sa.String(length=32), nullable=False),
    sa.Column('principal_id', sa.String(length=255), nullable=False),
    sa.Column('server_name', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('daily_call_limit', sa.Integer(), nullable=True),
    sa.Column('daily_cost_limit', sa.Float(), nullable=True),
    sa.Column('concurrent_limit', sa.Integer(), nullable=True),
    sa.Column('run_call_limit', sa.Integer(), nullable=True),
    sa.Column('max_run_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('call_cost_units', sa.Float(), nullable=False),
    sa.Column('warning_threshold', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('frozen', sa.Boolean(), nullable=False),
    sa.Column('temporary_override_json', sa.JSON(), nullable=True),
    sa.Column('temporary_override_expires_at', sa.DateTime(), nullable=True),
    sa.Column('reset_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['mcp_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_key', name='uq_mcp_quota_policy_scope')
    )
    with op.batch_alter_table('mcp_quota_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_quota_policies_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_quota_policies_frozen'), ['frozen'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_quota_policies_repo_id'), ['repo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_quota_policies_temporary_override_expires_at'), ['temporary_override_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_quota_policies_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repo_id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('principal_type', sa.String(length=32), nullable=False),
    sa.Column('principal_id', sa.String(length=255), nullable=False),
    sa.Column('delegated_identity_id', sa.String(length=36), nullable=True),
    sa.Column('user_input', sa.Text(), nullable=False),
    sa.Column('test_command', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('final_diff', sa.Text(), nullable=True),
    sa.Column('final_summary', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('test_result', sa.JSON(), nullable=True),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('feedback_status', sa.String(length=32), nullable=True),
    sa.Column('feedback_note', sa.Text(), nullable=True),
    sa.Column('feedback_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['delegated_identity_id'], ['mcp_delegated_identities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['mcp_tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_repo_id'), ['repo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('code_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repo_id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('symbol_name', sa.String(length=255), nullable=True),
    sa.Column('symbol_type', sa.String(length=64), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('embedding_id', sa.String(length=128), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('imports', sa.JSON(), nullable=False),
    sa.Column('exports', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['code_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('code_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_code_chunks_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_chunks_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_chunks_repo_id'), ['repo_id'], unique=False)

    op.create_table('mcp_quota_rejections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('repo_id', sa.String(length=36), nullable=True),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('principal_type', sa.String(length=32), nullable=False),
    sa.Column('principal_id', sa.String(length=255), nullable=False),
    sa.Column('server_name', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('retry_after_seconds', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['mcp_quota_policies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcp_quota_rejections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_quota_rejections_policy_id'), ['policy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_quota_rejections_reason'), ['reason'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_quota_rejections_repo_id'), ['repo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_quota_rejections_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_quota_rejections_server_name'), ['server_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_quota_rejections_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_quota_rejections_tool_name'), ['tool_name'], unique=False)

    op.create_table('agent_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('step_type', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=True),
    sa.Column('input_json', sa.JSON(), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_steps_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_steps_step_type'), ['step_type'], unique=False)

    op.create_table('mcp_tool_approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('qualified_name', sa.String(length=257), nullable=False),
    sa.Column('server_name', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('arguments_json', sa.JSON(), nullable=False),
    sa.Column('arguments_hash', sa.String(length=64), nullable=False),
    sa.Column('tool_schema_json', sa.JSON(), nullable=False),
    sa.Column('catalog_entry_json', sa.JSON(), nullable=False),
    sa.Column('policy_snapshot', sa.String(length=32), nullable=False),
    sa.Column('checkpoint_json', sa.JSON(), nullable=False),
    sa.Column('checkpoint_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.Column('decided_provider', sa.String(length=64), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('execution_started_at', sa.DateTime(), nullable=True),
    sa.Column('execution_finished_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcp_tool_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_tool_approvals_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_tool_approvals_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_tool_approvals_status'), ['status'], unique=False)

    op.create_table('mcp_tool_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('approval_id', sa.String(length=36), nullable=True),
    sa.Column('qualified_name', sa.String(length=257), nullable=False),
    sa.Column('server_name', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('arguments_json', sa.JSON(), nullable=False),
    sa.Column('arguments_hash', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('idempotency_mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('recovery_count', sa.Integer(), nullable=False),
    sa.Column('deduplication_hits', sa.Integer(), nullable=False),
    sa.Column('retry_safe', sa.Boolean(), nullable=False),
    sa.Column('lease_token', sa.String(length=64), nullable=True),
    sa.Column('lease_owner', sa.String(length=255), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('checkpoint_json', sa.JSON(), nullable=True),
    sa.Column('checkpoint_hash', sa.String(length=64), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('reconciliation_note', sa.Text(), nullable=True),
    sa.Column('reconciled_by', sa.String(length=255), nullable=True),
    sa.Column('reconciled_provider', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('reconciled_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['mcp_tool_approvals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcp_tool_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_tool_executions_approval_id'), ['approval_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_tool_executions_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_mcp_tool_executions_lease_expires_at'), ['lease_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_tool_executions_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_tool_executions_status'), ['status'], unique=False)

    op.create_table('mcp_quota_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('repo_id', sa.String(length=36), nullable=True),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('delegated_identity_id', sa.String(length=36), nullable=True),
    sa.Column('principal_type', sa.String(length=32), nullable=False),
    sa.Column('principal_id', sa.String(length=255), nullable=False),
    sa.Column('server_name', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('cost_units', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('lease_token', sa.String(length=64), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['mcp_tool_executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['mcp_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcp_quota_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_quota_events_delegated_identity_id'), ['delegated_identity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_quota_events_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_mcp_quota_events_lease_expires_at'), ['lease_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_quota_events_principal_id'), ['principal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_quota_events_principal_type'), ['principal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_quota_events_repo_id'), ['repo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_quota_events_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_quota_events_server_name'), ['server_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_quota_events_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_quota_events_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_quota_events_tool_name'), ['tool_name'], unique=False)

    op.create_table('mcp_quota_charges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.Column('cost_units', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['mcp_quota_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['mcp_quota_policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'policy_id', name='uq_mcp_quota_charge_event_policy')
    )
    with op.batch_alter_table('mcp_quota_charges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_quota_charges_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_quota_charges_policy_id'), ['policy_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mcp_quota_charges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_quota_charges_policy_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_quota_charges_event_id'))

    op.drop_table('mcp_quota_charges')
    with op.batch_alter_table('mcp_quota_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_quota_events_tool_name'))
        batch_op.drop_index(batch_op.f('ix_mcp_quota_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_quota_events_status'))
        batch_op.drop_index(batch_op.f('ix_mcp_quota_events_server_name'))
        batch_op.drop_index(batch_op.f('ix_mcp_quota_events_run_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_quota_events_repo_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_quota_events_principal_type'))
        batch_op.drop_index(batch_op.f('ix_mcp_quota_events_principal_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_quota_events_lease_expires_at'))
        batch_op.drop_index(batch_op.f('ix_mcp_quota_events_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_mcp_quota_events_delegated_identity_id'))

    op.drop_table('mcp_quota_events')
    with op.batch_alter_table('mcp_tool_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_tool_executions_status'))
        batch_op.drop_index(batch_op.f('ix_mcp_tool_executions_run_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_tool_executions_lease_expires_at'))
        batch_op.drop_index(batch_op.f('ix_mcp_tool_executions_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_mcp_tool_executions_approval_id'))

    op.drop_table('mcp_tool_executions')
    with op.batch_alter_table('mcp_tool_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_tool_approvals_status'))
        batch_op.drop_index(batch_op.f('ix_mcp_tool_approvals_run_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_tool_approvals_expires_at'))

    op.drop_table('mcp_tool_approvals')
    with op.batch_alter_table('agent_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_steps_step_type'))
        batch_op.drop_index(batch_op.f('ix_agent_steps_run_id'))

    op.drop_table('agent_steps')
    with op.batch_alter_table('mcp_quota_rejections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_quota_rejections_tool_name'))
        batch_op.drop_index(batch_op.f('ix_mcp_quota_rejections_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_quota_rejections_server_name'))
        batch_op.drop_index(batch_op.f('ix_mcp_quota_rejections_run_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_quota_rejections_repo_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_quota_rejections_reason'))
        batch_op.drop_index(batch_op.f('ix_mcp_quota_rejections_policy_id'))

    op.drop_table('mcp_quota_rejections')
    with op.batch_alter_table('code_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_chunks_repo_id'))
        batch_op.drop_index(batch_op.f('ix_code_chunks_language'))
        batch_op.drop_index(batch_op.f('ix_code_chunks_file_id'))

    op.drop_table('code_chunks')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_status'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_repo_id'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('mcp_quota_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_quota_policies_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_quota_policies_temporary_override_expires_at'))
        batch_op.drop_index(batch_op.f('ix_mcp_quota_policies_repo_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_quota_policies_frozen'))
        batch_op.drop_index(batch_op.f('ix_mcp_quota_policies_enabled'))

    op.drop_table('mcp_quota_policies')
    with op.batch_alter_table('mcp_delegated_oauth_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_delegated_oauth_states_expires_at'))

    op.drop_table('mcp_delegated_oauth_states')
    with op.batch_alter_table('mcp_delegated_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_delegated_identities_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_delegated_identities_subject'))
        batch_op.drop_index(batch_op.f('ix_mcp_delegated_identities_server_name'))
        batch_op.drop_index(batch_op.f('ix_mcp_delegated_identities_revoked'))

    op.drop_table('mcp_delegated_identities')
    with op.batch_alter_table('mcp_access_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_access_grants_tool_name'))
        batch_op.drop_index(batch_op.f('ix_mcp_access_grants_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_access_grants_server_name'))
        batch_op.drop_index(batch_op.f('ix_mcp_access_grants_repo_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_access_grants_principal_type'))
        batch_op.drop_index(batch_op.f('ix_mcp_access_grants_principal_id'))

    op.drop_table('mcp_access_grants')
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluations_task_type'))
        batch_op.drop_index(batch_op.f('ix_evaluations_repo_id'))
        batch_op.drop_index(batch_op.f('ix_evaluations_evaluation_run_id'))

    op.drop_table('evaluations')
    with op.batch_alter_table('code_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_files_repo_id'))
        batch_op.drop_index(batch_op.f('ix_code_files_language'))

    op.drop_table('code_files')
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repositories_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_repositories_status'))

    op.drop_table('repositories')
    with op.batch_alter_table('mcp_tenant_server_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_tenant_server_bindings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_tenant_server_bindings_server_name'))

    op.drop_table('mcp_tenant_server_bindings')
    with op.batch_alter_table('mcp_tenant_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_tenant_memberships_tenant_id'))

    op.drop_table('mcp_tenant_memberships')
    with op.batch_alter_table('mcp_server_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_server_revisions_server_id'))

    op.drop_table('mcp_server_revisions')
    with op.batch_alter_table('mcp_delegated_oauth_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_delegated_oauth_providers_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_delegated_oauth_providers_server_name'))

    op.drop_table('mcp_delegated_oauth_providers')
    with op.batch_alter_table('mcp_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_credentials_server_id'))

    op.drop_table('mcp_credentials')
    with op.batch_alter_table('mcp_tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_tenants_slug'))

    op.drop_table('mcp_tenants')
    with op.batch_alter_table('mcp_server_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_server_registrations_validation_status'))
        batch_op.drop_index(batch_op.f('ix_mcp_server_registrations_name'))
        batch_op.drop_index(batch_op.f('ix_mcp_server_registrations_enabled'))

    op.drop_table('mcp_server_registrations')
    with op.batch_alter_table('mcp_server_health', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_server_health_last_probe_status'))
        batch_op.drop_index(batch_op.f('ix_mcp_server_health_cooldown_until'))
        batch_op.drop_index(batch_op.f('ix_mcp_server_health_circuit_state'))

    op.drop_table('mcp_server_health')
    with op.batch_alter_table('evaluation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_runs_task_type'))
        batch_op.drop_index(batch_op.f('ix_evaluation_runs_status'))
        batch_op.drop_index(batch_op.f('ix_evaluation_runs_dataset_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_runs_dataset_id'))

    op.drop_table('evaluation_runs')
    with op.batch_alter_table('evaluation_datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_datasets_task_type'))
        batch_op.drop_index(batch_op.f('ix_evaluation_datasets_name'))
        batch_op.drop_index(batch_op.f('ix_evaluation_datasets_baseline_run_id'))

    op.drop_table('evaluation_datasets')
    with op.batch_alter_table('evaluation_dataset_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_dataset_snapshots_version'))
        batch_op.drop_index(batch_op.f('ix_evaluation_dataset_snapshots_task_type'))
        batch_op.drop_index(batch_op.f('ix_evaluation_dataset_snapshots_dataset_id'))

    op.drop_table('evaluation_dataset_snapshots')
    # ### end Alembic commands ###
