"""quota reconciliation evidence

Revision ID: d61724294075
Revises: cba2490cda76
Create Date: 2026-07-14 12:39:35.512623
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd61724294075'
down_revision: Union[str, None] = 'cba2490cda76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_quota_reconciliations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('repaired', sa.Boolean(), nullable=False),
    sa.Column('drift_json', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcp_quota_reconciliations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_quota_reconciliations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_quota_reconciliations_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mcp_quota_reconciliations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_quota_reconciliations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_quota_reconciliations_status'))

    op.drop_table('mcp_quota_reconciliations')
    # ### end Alembic commands ###
