apiVersion: v1
kind: ServiceAccount
metadata:
  name: sandbox-execution-plane
  namespace: codemate-sandbox
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sandbox-job-controller
  namespace: codemate-sandbox
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sandbox-job-controller
  namespace: codemate-sandbox
subjects:
  - kind: ServiceAccount
    name: sandbox-execution-plane
    namespace: codemate-sandbox
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sandbox-job-controller
